### ISSUE TITLE
CORS error with JSClient

### ISSUE THREAD

**Issue by Poorva17** [cornerman/covenant#2]
JVMClient is working as expected, but JSClient is giving us CORS error. 

I guess adding  _Access-Control-Allow-Origin: *_ header in client request should fix it but could not find a way in the API to do so.

**Comment by cornerman** [comment]
Good point! For the JSClient, this is the cross-origin protection of the browser kicking in. The client will make a request with an `Origin` header and check whether the response contains an `Access-Control-Allow-Origin` header for the specified origin (this might also be done in a so called preflight request).

What you can do is handle CORS in your akka server. There is library for CORS for akka-http: https://github.com/lomigmegard/akka-http-cors

With this, you can just use the normal routing dsl, as `AkkaHttpRoute.fromFutureRouter` just returns an akka `Route`:
```
val route = cors() { // see readme of akka-http-cors for more settings
  AkkaHttpRoute.fromFutureRouter(router)
}

Http().bindAndHandle(route, interface = "0.0.0.0", port = port)
```

Does that work for you?

**Comment by cornerman** [comment]
For the `Access-Control-Allow-Origin` header - this is not a request header, but a response header and is set by the server (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin). The request needs to contain an `Origin` header, which should be done automatically by the browser.

Do you have this error in the client or in the server? I am using the same library and actually explicitly provide the allowed-origin domains when I set up CORS. Can you try this:

```scala
val corsSettings = CorsSettings.defaultSettings.copy(
  allowedOrigins = HttpOriginRange(HttpOrigin("example.com"))
val route = cors(corsSettings) {
  AkkaHttpRoute.fromApiRouter(jsonRouter, apiConfig)
}
```

**Comment by Poorva17** [comment]
Ok, so the issue was because we were loading html from local disk (file://) which triggers strict security restriction on chrome. 

We successfully managed to load it via firefox and the akka-http-cors default settings. 

We can close this issue.

**Comment by cornerman** [comment]
Ah good to know. Glad that it works now!
