### ISSUE TITLE
Add response header

### ISSUE THREAD

**Issue by Poorva17** [cornerman/covenant#4]
We are using circe for serialization. It's working fine but we are getting response header as `Content-Type: text/plain`

We want response header to be 'content-type-application/json'.  We tried setting header with responseWithHeaders() method. But akka http is giving error - `Explicitly set HTTP header 'Content-Type: application/json' is ignored, explicit 'Content-Type' header is not allowed. Set 'HttpResponse.entity.contentType' instead.`

But we don't have handle of response entity. 

Any way to solve this?

**Comment by cornerman** [comment]
For the `AkkaHttpRoute` factory, you can pass your own `ToResponseMarshaller` implicitly. So, you should be able to achieve this by defining:

```scala
implicit val jsonMarshaller: ToResponseMarshaller[String] = Marshaller.withFixedContentType(ContentTypes.`application/json`) { s =>
  HttpResponse(status = StatusCodes.OK, entity = HttpEntity(ContentTypes.`application/json`, s))
}
```

Then you can use this marshaller with `AkkaHttpRoute.fromApiRouter` etc. Does that work for you?

**Comment by Poorva17** [comment]
Thank you @cornerman . 

We did not have to use `AkkaHttpRoute.fromApiRouter`. We used `AkkaHttpRoute.fromFutureRouter` and passed 
`implicit val jsonMarshaller: ToResponseMarshaller[String] = Marshaller.fromResponse.compose[String] { str =>
    HttpResponse(
      status = StatusCodes.OK,
      entity = HttpEntity(ContentTypes.`application/json`, str)
    )
  }` . This worked for us. :)

**Comment by cornerman** [comment]
Great! I am closing this issue, but feel free to reopen if there is something.
