### ISSUE TITLE
troubles with java.util.Date 

### ISSUE THREAD

**Issue by elyphas** [cornerman/covenant#43]
I have an error:
```scala
WSCovenant.scala:28:40: could not find implicit value for parameter deserializer: chameleon.Deserializer[Either[String,List[GralDataPedido]],java.nio.ByteBuffer]
[error]   val api = client.sendWithDefault.wire[Api[Future]]
```
```scala
WebService.scala:59:84: could not find implicit value for parameter serializer: chameleon.Serializer[Either[String,List[GralDataPedido]],java.nio.ByteBuffer]
[error]   val router = Router[ ByteBuffer, Dsl.ApiFunction ].route[ Api[ Dsl.ApiFunction ]]( ApiImpl )
```
When I try to use the `java.util.Date` type  in my `case class`

Any idea to solve this?
Thanks in advance!

**Comment by cornerman** [comment]
@elyphas Which serializer are you using? Is it circe? As far as I know, there is often times no serializer for `java.util.Date` but normally only for `ZonedDateTime`.

**Comment by elyphas** [comment]
@cornerman, boopickle
now I trying with `java.sql.Date` but the same results. this because it represents a field in a table on postgresql.

thanks

**Comment by elyphas** [comment]
solved.

  implicit val datePickler = transformPickler((t: Long) => new java.util.Date(t))(_.getTime)
