### ISSUE TITLE
error with Serializer

### ISSUE THREAD

**Issue by elyphas** [cornerman/covenant#45]
Someone could tell me, please, What is wrong with this code?

https://gist.github.com/elyphas/a252ef08231648df85c10d30007f3905

The error is this:
```scala
could not find implicit value for parameter serializer: 
chameleon.Serializer[Either[String,List[spatutorial.shared.GralDataPedido]],java.nio.ByteBuffer]
[error]         
val router = Router[ByteBuffer, Dsl.ApiFunction].route[Api[Dsl.ApiFunction]](ApiImpl)
```

**Comment by cornerman** [comment]
@elyphas I guess you are using boopickle for serialization. Have you tried importing the auto-derivation for boopickle with `import boopickle.Default._`?

**Comment by elyphas** [comment]
Yes

**Comment by cornerman** [comment]
So, it works now? :)

**Comment by elyphas** [comment]
not, I had before the I made the question.

**Comment by cornerman** [comment]
Ok - no worries. Then boopickle cannot derive a serializer for `spatutorial.shared.GralDataPedido`, because there are definitely serializer for `Either`, `String`, and `List`. There must be something inside that data type.

**Comment by elyphas** [comment]
the thing is only in the test side. 
I have the problem because it works fine

**Comment by elyphas** [comment]
> Ok - no worries. Then boopickle cannot derive a serializer for `spatutorial.shared.GralDataPedido`, because there are definitely serializer for `Either`, `String`, and `List`. There must be something inside that data type.

I think the problem with java.util.Date

**Comment by cornerman** [comment]
> I think the problem with java.util.Date

Sounds probable. I think, we discussed this before here: https://github.com/cornerman/covenant/issues/43

**Comment by elyphas** [comment]
Yes it works
Yes, sorry I forgot it to include it in my test `class`

**Comment by elyphas** [comment]
@cornerman ; Thank you!. :)

**Comment by cornerman** [comment]
Great!
